version: '3'

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - maria_database:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
    networks:
      - inception
  
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    volumes:
      - wp_data:/var/www/html
    ports:
      - 443:443
    restart: always
    depends_on:
      - wordpress
    networks:
      - inception

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    environment:
      MARIADB_DBNAME: wordpress
      MARIADB_USER: wp_user
      MARIADB_PASS: biden_1234
      MARIADB_HOST: mariadb:3306
    volumes:
      - wp_data:/var/www/html
    depends_on:
      - mariadb
    ports:
      - 9000:9000
    restart: always
    networks:
      - inception

networks:
  inception:
    driver: bridge

volumes:
  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ochoumou/inception-data/wordpress
  maria_database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ochoumou/inception-data/mysql

