version: '3'

services:
  mariadb:
    build: ./requirements/mariadb
    volumes:
      - maria_database:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
    networks:
      - inception
  
  nginx:
    build: ./requirements/nginx
    volumes:
      - wp_data:/var/www/html
    ports:
      - 443:443
    restart: always
    depends_on:
      - wordpress
    networks:
      - inception

  wordpress:
    build: ./requirements/wordpress
    environment:
      MARIADB_DBNAME: wordpress
      MARIADB_USER: wp_user
      MARIADB_PASS: biden_1234
      MARIADB_HOST: mariadb:3306
    volumes:
      - wp_data:/var/www/html
    depends_on:
      - mariadb
    ports:
      - 9000:9000
    restart: always
    networks:
      - inception

networks:
  inception:
    driver: bridge

volumes:
  wp_data:
    driver: local
    driver_opts:
      type: none
      device: /home/sn4r7/42/docker/mysql
      o: bind
  maria_database:
    driver: local
    driver_opts:
      type: none
      device: /home/sn4r7/42/docker/wordpress
      o: bind

