version: '3'

services:
  mariadb:
    container_name: mariadb
    build: 
      context: ./requirements/mariadb
      args:
        MARIADB_DBNAME: ${MARIADB_DBNAME}
        MARIADB_PASS: ${MARIADB_PASS}
        MARIADB_USER: ${MARIADB_USER}
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
    networks:
      - inception
  
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    volumes:
      - wpdata:/var/www/html/wordpress
    ports:
      - 443:443
    restart: always
    depends_on:
      - wordpress
      - static
      - cadvisor
    networks:
      - inception

  wordpress:
    container_name: wordpress
    build: 
      context: ./requirements/wordpress
      args:
        MARIADB_DBNAME: ${MARIADB_DBNAME}
        MARIADB_PASS: ${MARIADB_PASS}
        MARIADB_USER: ${MARIADB_USER}
        MARIADB_HOST: ${MARIADB_HOST}
        WP_USER: ${WP_USER}
        WP_PASS: ${WP_PASS}
    volumes:
      - wpdata:/var/www/html/wordpress
    depends_on:
      - mariadb
      - redis
    ports:
      - 9000:9000
    restart: always
    networks:
      - inception

  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer
    depends_on:
      - mariadb
    ports:
      - 9001:9001
    restart: always
    networks:
      - inception

  cadvisor:
    container_name: cadvisor
    build: ./requirements/bonus/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - 8080:8080
    restart: always
    networks:
      - inception

  static:
    container_name: static
    build: ./requirements/bonus/static
    ports:
      - 2500:2500
    restart: always
    networks:
      - inception

  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    ports:
      - 6379:6379
    restart: always
    networks:
      - inception

  ftp:
    container_name: ftp
    build: 
      context: ./requirements/bonus/ftp
      args:
        - FTP_USER=${FTP_USER}
        - FTP_PASS=${FTP_PASS}
    depends_on:
      - nginx
      - wordpress
      - mariadb
    volumes:
      - wpdata:/var/www/html/wordpress
    ports:
      - 21:21
      - "50000-50010:50000-50010"
    restart: always
    networks:
      - inception

networks:
  inception:
    driver: bridge

volumes:
  wpdata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/sn4r7/docker/wordpress
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/sn4r7/docker/sql

